name: Deploy to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker images
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          
          cd "WebDev Darshan"
          docker build -t $DOCKERHUB_USERNAME/echo-"WebDev-Darshan" .
          docker push $DOCKERHUB_USERNAME/echo-"WebDev-Darshan"
          cd ..

          cd "WebDev Pulkit"
          docker build -t $DOCKERHUB_USERNAME/echo-"WebDev-Pulkit" .
          docker push $DOCKERHUB_USERNAME/echo-"WebDev-Pulkit"
          cd ..

          cd "WebDev Rachit"
          docker build -t $DOCKERHUB_USERNAME/echo-"WebDev-Rachit" .
          docker push $DOCKERHUB_USERNAME/echo-"WebDev-Rachit"
          cd ..

          cd "WebDev Raghav"
          docker build -t $DOCKERHUB_USERNAME/echo-"WebDev-Raghav" .
          docker push $DOCKERHUB_USERNAME/echo-"WebDev-Raghav"
          cd ..

      - name: Deploy MySQL database
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        run: |
          docker run -d --name mysql-container -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD -e MYSQL_DATABASE=$MYSQL_DATABASE -p 3306:3306 mysql:latest

      - name: Clean up old containers
        run: |
          docker ps -aq | xargs docker stop
          docker ps -aq | xargs docker rm
      # ... (previous steps)

      - name: Start Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      # ... (other steps)

